trigger:
- master

strategy:
  matrix:
    windows:
      operatingSystem: 'windows-latest'
    mac:
      operatingSystem: 'macos-latest'
pool:
  vmImage: $(operatingSystem)

steps:
- script: echo Running on $(operatingSystem)
  displayName: 'Run a one-line script'